### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by kaylamt**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Kayla!
Good job! Some corrections need to be made, but on the whole, the project is very impressive!

Please note that dev version of the project fails to compile. Please fix.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* The content of section `about` isn't aligned correctly: https://prnt.sc/1176mgz
* The image isn't loaded: https://prnt.sc/1176pme and the card layout is incorrect because of it.
* popup opened: https://prnt.sc/1176r47
* the header isn't centered horizontally: https://prnt.sc/1176ug1 and elements have incorrect font-weight
* incorrect font-family: https://prnt.sc/1176w5y, chech the "Registration successful" popup too
* the card layout on mobile screen is incorrect: https://prnt.sc/1176yco
* The background image on mobile screens should be different
* Incorrect layout on tablets: https://prnt.sc/11772c2. There should be three cards in a row on tablet and desktop resolutions.
* Section `about` looks incorrectly: https://prnt.sc/11773iw
* Incorrect line-height: https://prnt.sc/11776ko
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
The links to external pages should open in new tabs.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
* The images in cards lose their proportions on intermediate resolutions
* Text is too narrow on intermediate resolutions: https://prnt.sc/117745o
- [x]  There are no validation errors.
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
The cards gallery should be a list <ul>, as well as the links in the header and footer.
All paragraphs should be <p> elements, not <div>: https://prnt.sc/1177dxr Please correct all similar issues.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.
* Popups aren't opening on mobile screens

- The markup has been converted into JSX:
	- [ ]  The markup is included within parentheses ( ).
	https://prnt.sc/1177w6r
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.

* Element is used outside of its block: https://prnt.sc/1177atc (please correct all similar issues)

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
The search form input isn't highlighted
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [ ]  System fonts are connected as alternatives to each of your fonts.
Please, correct all similar cases: https://prnt.sc/117810v
- [x]  Raster and vector images have been optimized.

## Number of points: 41

**Comment by kaylamt** [comment]
Thank you for your notes and suggestions! For the dev version failing to compile, do you mean when I run npm start? This is working for me, let me know if I misunderstood. Thanks!

**Comment by ImaliaNsk** [comment]
Hi Kayla! Thanks for the corrections made, they look great and you're on the right track! However, some issues are still left to correct, some mismatches to the design are left.

As for the error while compilation, please nevermind, that was a glitch on my side, the project complies fine. Sorry for the confusion I caused.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The content of section `about` isn't aligned correctly: https://prnt.sc/1182mz8
* There should be three cards in a row on tablet and desktop resolutions https://prnt.sc/1182or1
* Registration successful popup: https://prnt.sc/1182t5c
* The background image on mobile screens should be different

- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.

* The images in cards lose their proportions on intermediate resolutions: https://prnt.sc/1182x99 https://prnt.sc/1182wdz. Also the text get outside of its containers

- [ ]  There are no validation errors.

* `ul` is used incorrectly: only `<li>` elements are allowed as direct descendants of `<ul>`

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div>` containers.
* The cards gallery should be a list `<ul>`, as well as the links in the header and footer. For the links it's also possible to use `<nav>` without `<ul>`
In the news cards list, `<ul>` should be used to contain the cards, each card will be a list item `<li>`. Please, don't use `<ul>` here: https://prnt.sc/11832z1, those are not the lists.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [ ]  The markup is included within parentheses ( ).
	* https://prnt.sc/11834ab
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.

* Element is used outside of its block:https://prnt.sc/1182yoe  https://prnt.sc/1177atc (please correct all similar issues)

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 59

**Comment by ImaliaNsk** [comment]
Hi Kayla! Congratulations, the project has passed code review. I wish you good luck on the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
* The images in cards lose their proportions on intermediate resolutions: https://prnt.sc/1182x99 https://prnt.sc/1182wdz. Also the text get outside of its containers
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 86

**Pull request merged**
